name: procolocowork
favicon: null
layout_spectrum: 0.21578053198754787
typography_spectrum: 0.6484849490225315
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.21284075430594385
  lightness: 0.49591560545377433
  saturation: 0.3274801289662719
  rhythmicContrast: 0.40019829175435007
purpose: []
